# Generated by Django 4.1.7 on 2023-04-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodOfStudy', models.TextField(blank=True, max_length=1000, verbose_name='Период обучения')),
                ('theNameOfTheInstitution', models.TextField(blank=True, max_length=1000, verbose_name='Название заведения/курсов')),
                ('receivedSkills', models.TextField(blank=True, max_length=1000, verbose_name='Полученные умения')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=1000, verbose_name='Клиент')),
                ('Photos', models.ImageField(blank=True, upload_to='', verbose_name='Лого клиента')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Сотрудничество',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название проекта')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('Preview', models.ImageField(upload_to='', verbose_name='Преью')),
                ('Photos1', models.ImageField(blank=True, upload_to='', verbose_name='Фото 1')),
                ('Photos2', models.ImageField(blank=True, upload_to='', verbose_name='Фото 2')),
                ('Photos3', models.ImageField(blank=True, upload_to='', verbose_name='Фото 3')),
                ('Photos4', models.ImageField(blank=True, upload_to='', verbose_name='Фото 4')),
                ('Photos5', models.ImageField(blank=True, upload_to='', verbose_name='Фото 5')),
                ('Photos6', models.ImageField(blank=True, upload_to='', verbose_name='Фото 6')),
                ('Photos7', models.ImageField(blank=True, upload_to='', verbose_name='Фото 7')),
                ('Photos8', models.ImageField(blank=True, upload_to='', verbose_name='Фото 8')),
                ('Photos9', models.ImageField(blank=True, upload_to='', verbose_name='Фото 9')),
                ('Photos10', models.ImageField(blank=True, upload_to='', verbose_name='Фото 10')),
                ('linkVK', models.CharField(blank=True, max_length=50, verbose_name='VK')),
                ('linkTwitter', models.CharField(blank=True, max_length=50, verbose_name='Twitter')),
                ('linkInstagram', models.CharField(blank=True, max_length=50, verbose_name='Instagram')),
                ('linkRarible', models.CharField(blank=True, max_length=50, verbose_name='Rarible')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['time_create', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(upload_to='', verbose_name='Фавикон сайта')),
                ('background', models.ImageField(upload_to='', verbose_name='Фон сайта')),
                ('contactPhoto', models.ImageField(upload_to='', verbose_name="Фон 'Контакты'")),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('photo', models.ImageField(upload_to='', verbose_name="Фото 'О себе'")),
                ('skills', models.TextField(blank=True, max_length=1000, verbose_name='Навыки')),
                ('biography', models.TextField(blank=True, max_length=1000, verbose_name='Биография')),
                ('site_quote', models.TextField(blank=True, max_length=500, verbose_name='Цитата')),
                ('owner_site_quote', models.CharField(blank=True, max_length=50, verbose_name='Автор цитаты')),
            ],
            options={
                'verbose_name': 'Основные параметры',
                'verbose_name_plural': 'Основные параметры',
            },
        ),
    ]
