# Generated by Django 4.0.3 on 2022-07-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(upload_to='', verbose_name='Фавикон сайта')),
                ('background', models.ImageField(upload_to='', verbose_name='Фон сайта')),
                ('contactPhoto', models.ImageField(upload_to='', verbose_name="Фон 'Контакты'")),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('photo', models.ImageField(upload_to='', verbose_name="Фото 'О себе'")),
                ('skills', models.TextField(blank=True, max_length=1000, verbose_name='Навыки')),
                ('biography', models.TextField(blank=True, max_length=1000, verbose_name='Биография')),
                ('site_quote', models.TextField(blank=True, max_length=500, verbose_name='Цитата')),
                ('owner_site_quote', models.CharField(blank=True, max_length=50, verbose_name='Автор цитаты')),
            ],
            options={
                'verbose_name': 'Основные параметры',
                'verbose_name_plural': 'Основные параметры',
            },
        ),
    ]
