# Generated by Django 4.0.3 on 2022-07-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodOfStudy', models.TextField(blank=True, max_length=1000, verbose_name='Период обучения')),
                ('theNameOfTheInstitution', models.TextField(blank=True, max_length=1000, verbose_name='Название заведения/курсов')),
                ('receivedSkills', models.TextField(blank=True, max_length=1000, verbose_name='Полученные умения')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
            },
        ),
    ]
