# Generated by Django 4.0.3 on 2022-07-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=1000, verbose_name='Клиент')),
                ('Photos', models.ImageField(blank=True, upload_to='', verbose_name='Лого клиента')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиент',
            },
        ),
    ]
