# Generated by Django 4.0.3 on 2022-07-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_alter_partners_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partners',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
